#!/usr/bin/env python3
"""
Build the AU01 whitespace OpenFOAM case from the FreeCAD Rev E CFD export.

The point of this generator is that geometry is *read*, not transcribed:
every plane, extent and rack load comes from cfd_export_params.json and the
STL files themselves, both copied verbatim out of the CAD model. Only
solver-side choices live in system/au01Parameters.

    ./make_au01_dicts.py case-au01
"""

import json
import math
import os
import sys
from collections import OrderedDict

CP = 1005.0          # J/kg/K, matches constant/thermophysicalProperties
R_AIR = 287.05
P_ATM = 101325.0


# --------------------------------------------------------------------------
# inputs
# --------------------------------------------------------------------------

def read_params(path):
    """Parse the plain key/value parameter file, ignoring # comments."""
    out = {}
    with open(path) as fh:
        for line in fh:
            line = line.split('#', 1)[0].strip()
            if not line:
                continue
            bits = line.split(None, 1)
            if len(bits) == 2:
                out[bits[0]] = bits[1].strip()
    return out


def stl_solids(path):
    """Return OrderedDict name -> (xmin,xmax,ymin,ymax,zmin,zmax)."""
    solids = OrderedDict()
    name = None
    with open(path, errors='replace') as fh:
        for line in fh:
            s = line.strip()
            if s.startswith('solid'):
                name = s[5:].strip() or 'solid%d' % len(solids)
                solids[name] = [1e30, -1e30, 1e30, -1e30, 1e30, -1e30]
            elif s.startswith('vertex') and name is not None:
                p = [float(v) for v in s.split()[1:4]]
                b = solids[name]
                for i in range(3):
                    b[2 * i] = min(b[2 * i], p[i])
                    b[2 * i + 1] = max(b[2 * i + 1], p[i])
    return solids


def extract_roof(src, dst):
    """Write only the roof solids of room_shell.stl to their own file.

    The vertical walls and the floor coincide exactly with blockMesh faces, so
    handing them to snappyHexMesh only invites coincident-surface trouble. The
    gable is the one part of the shell the background mesh cannot represent.
    """
    keep, out, name = False, [], None
    with open(src, errors='replace') as fh:
        for line in fh:
            s = line.strip()
            if s.startswith('solid'):
                name = s[5:].strip()
                keep = 'roof' in name
            if keep:
                out.append(line)
            if s.startswith('endsolid'):
                keep = False
    if not out:
        raise SystemExit('no roof solids found in %s' % src)
    with open(dst, 'w') as fh:
        fh.writelines(out)


# --------------------------------------------------------------------------

def box_solid(name, x0, x1, y0, y1, z0, z1):
    """One axis-aligned box as an ASCII STL solid."""
    v = [(x0, y0, z0), (x1, y0, z0), (x1, y1, z0), (x0, y1, z0),
         (x0, y0, z1), (x1, y0, z1), (x1, y1, z1), (x0, y1, z1)]
    quads = [((0, 3, 2, 1), (0, 0, -1)), ((4, 5, 6, 7), (0, 0, 1)),
             ((0, 1, 5, 4), (0, -1, 0)), ((3, 7, 6, 2), (0, 1, 0)),
             ((0, 4, 7, 3), (-1, 0, 0)), ((1, 2, 6, 5), (1, 0, 0))]
    out = ['solid %s\n' % name]
    for idx, n in quads:
        for tri in ((idx[0], idx[1], idx[2]), (idx[0], idx[2], idx[3])):
            out.append('  facet normal %g %g %g\n    outer loop\n' % n)
            for i in tri:
                out.append('      vertex %.6f %.6f %.6f\n' % v[i])
            out.append('    endloop\n  endfacet\n')
    out.append('endsolid %s\n' % name)
    return ''.join(out)


HEADER = ('// GENERATED by make_au01_dicts.py - do not edit.\n'
          '// Geometry comes from system/cfd_export_params.json and\n'
          '// constant/triSurface/*.stl (FreeCAD Rev E export).\n'
          '// Solver settings come from system/au01Parameters.\n')


def foam(cls, obj):
    return 'FoamFile { version 2.0; format ascii; class %s; object %s; }\n' % (cls, obj)


class Case(object):

    def __init__(self, case):
        self._extra = []
        self._gantry_file, self._raised = 'gantry.stl', 0
        self.case = case
        self.sys = os.path.join(case, 'system')
        self.tri = os.path.join(case, 'constant', 'triSurface')
        self.p = read_params(os.path.join(self.sys, 'au01Parameters'))
        with open(os.path.join(self.sys, 'cfd_export_params.json')) as fh:
            self.g = json.load(fh)
        self._geometry()

    @staticmethod
    def _ncells(lo, hi, d):
        """How many cell centres of pitch d fall inside [lo, hi]."""
        first = math.ceil(lo / d - 0.5 - 1e-9)
        last = math.floor(hi / d - 0.5 + 1e-9)
        return max(0, int(last - first + 1))

    @staticmethod
    def _zone_faces(lo, hi, d):
        """The mesh face planes bounding the cells whose centres lie in [lo, hi].

        boxToFace selects by face centre, so a baffle box must straddle a real
        face plane. Centring one on the STL's rack top (1.9799) missed the mesh
        face at 2.000 entirely and selected nothing - a silent no-op that would
        have looked like a completed run with the fix applied.
        """
        first = math.ceil(lo / d - 0.5 - 1e-9)
        last = math.floor(hi / d - 0.5 + 1e-9)
        return first * d, (last + 1) * d

    def f(self, key):
        return float(self.p[key])

    def i(self, key):
        return int(float(self.p[key]))

    # ---- geometry ------------------------------------------------------

    def _geometry(self):
        g, p = self.g, self.p
        s = float(g['scale'])
        room = g['room']
        self.x0, self.x1 = [v * s for v in room['x']]
        self.y0, self.y1 = [v * s for v in room['y']]
        self.eave = room['eave'] * s
        self.apex = room['apex'] * s

        c = self.f('cellSize')
        # y divides exactly; x does not (24.130 is not a multiple of 50 mm), so
        # take the nearest whole number of cells and let the cell be 0.08 %
        # short rather than move the wall off a mesh face.
        self.nx = max(1, int(round((self.x1 - self.x0) / c)))
        self.ny = max(1, int(round((self.y1 - self.y0) / c)))
        self.dx = (self.x1 - self.x0) / self.nx
        self.dy = (self.y1 - self.y0) / self.ny
        # The box top must sit at or above the apex. Keep dz exactly cellSize so
        # the rack tops (2.0) and the bulkhead top (3.0) land on cell faces.
        self.nz = int(math.ceil(self.apex / c - 1e-9))
        self.dz = c
        self.z0, self.z1 = 0.0, self.nz * c

        fw = g['fanwall']
        self.fw_y = [v * s for v in fw['y']]
        self.fw_top = fw['top'] * s
        self.fw_split = fw['module_split'] * s
        self.modules = self.i('modulesPerEnd')
        # west unit discharges +x from its high-x face; east unit discharges -x.
        wx = [v * s for v in fw['w_x']]
        ex = [v * s for v in fw['e_x']]
        self.ends = OrderedDict()
        self.ends['W'] = dict(body=wx, supply_x=wx[1], intake_x=wx[0], sign=+1.0)
        self.ends['E'] = dict(body=ex, supply_x=ex[0], intake_x=ex[1], sign=-1.0)

        self.module_z = []
        for m in range(self.modules):
            self.module_z.append((m * self.fw_split, (m + 1) * self.fw_split))

        # racks straight out of the STL, loads out of the schedule
        solids = stl_solids(os.path.join(self.tri, 'racks_body.stl'))
        sched = g['rack_schedule_kw']
        rows = g['racks']['rows']
        self.racks = []
        for name, b in solids.items():
            tag = name.split('_', 1)[1]                 # A01-HD
            row = tag[0]
            if tag not in sched:
                raise SystemExit('rack %s is not in rack_schedule_kw' % tag)
            iy = rows[row]['intake_y'] * s
            ey = rows[row]['exhaust_y'] * s
            self.racks.append(dict(
                tag=tag, row=row,
                x0=b[0], x1=b[1], y0=b[2], y1=b[3], z0=b[4], z1=b[5],
                intake_y=iy, dir=(1.0 if ey > iy else -1.0),
                kW=float(sched[tag])))
        if len(self.racks) != len(sched):
            raise SystemExit('racks_body.stl has %d solids, schedule has %d'
                             % (len(self.racks), len(sched)))

        # 610 mm pitch on a 50 mm grid is not commensurate, so a rack zone
        # captures 11 or 12 cell columns depending on where it falls. Measure
        # what each zone will actually hold and size its fan from that, or
        # equal-load racks would end up moving unequal air.
        for r in self.racks:
            r['ncx'] = self._ncells(r['x0'] + 0.2 * self.dx,
                                    r['x1'] - 0.2 * self.dx, self.dx)
            r['ncz'] = self._ncells(r['z0'] - 0.2 * self.dz,
                                    r['z1'] - 0.2 * self.dz, self.dz)
            r['area'] = r['ncx'] * self.dx * r['ncz'] * self.dz

        # ---- duty ------------------------------------------------------
        self.Tsup = self.f('supplyTemp_C') + 273.15
        self.rho = P_ATM / (R_AIR * self.Tsup)
        self.dT = self.f('serverDeltaT_K')

        self.mod_area = (self.fw_y[1] - self.fw_y[0]) * (self.fw_top / self.modules)
        # Supply can be throttled below nameplate. With a capped cold side the
        # surplus has nowhere to go: the fan walls move 84.65 kg/s and the racks
        # draw 48.8, and you cannot push the difference through a sealed pod.
        self.throttle = float(self.p.get('supplyThrottle', 1.0))
        q_end = self.f('unitAirflow_m3h') * self.throttle / 3600.0
        self.mod_flow = q_end / self.modules
        self.mod_mdot = self.mod_flow * self.rho
        self.supply_U = self.mod_flow / self.mod_area

        off = self.p.get('unitsOff', 'none').split()
        self.off = set() if off == ['none'] else set(off)
        for tag in self.off:
            if tag[0] not in self.ends or not (1 <= int(tag[1:]) <= self.modules):
                raise SystemExit('unitsOff: %r is not a module (W1 W2 E1 E2)' % tag)

        # Return plenum and pod-end enclosure. Neither exists in the Rev E
        # export; both are generated here as axis-aligned boxes so the option can
        # be tested before it goes back into CAD.
        self.bands = int(float(self.p.get('intakeBands', 4)))
        self.plenumZ = float(self.p.get('plenumFloorZ', 0.0))
        self.deckT = float(self.p.get('plenumDeckThickness', 0.05))
        self.sealPodEnds = self.p.get('sealPodEnds', '0') != '0'

        self.solver = self.p.get('solver', 'buoyantSimpleFoam')
        self.transient = self.solver.endswith('PimpleFoam')

        self.load_kW = sum(r['kW'] for r in self.racks)
        self.demand = self.load_kW * 1000.0 / (CP * self.dT)
        self.supply_kgs = (len(self.ends) * self.modules - len(self.off)) \
            * self.mod_flow * self.rho
        self.cap_kW = self.f('unitCapacity_kW') * len(self.ends) \
            * (1.0 - len(self.off) / float(len(self.ends) * self.modules))

    # ---- helpers -------------------------------------------------------

    def write(self, rel, text):
        path = os.path.join(self.case, rel)
        d = os.path.dirname(path)
        if d and not os.path.isdir(d):
            os.makedirs(d)
        with open(path, 'w') as fh:
            fh.write(text)

    def patches(self):
        """Every generated fan wall patch, in emit order."""
        out = []
        for end in self.ends:
            for m in range(1, self.modules + 1):
                out.append(('supply%s%d' % (end, m), end, m))
        for end in self.ends:
            for m in range(1, self.modules + 1):
                out.append(('intake%s%d' % (end, m), end, m))
        return out

    def live(self, name):
        """Is this patch a working fan wall module?"""
        return name[-2:] not in self.off

    # ---- dictionaries --------------------------------------------------

    def extra_stls(self):
        """Write the solids that are not in the CAD export yet.

        The deck's TOP is flush with the fan wall top, so its thickness eats into
        the cold side rather than into the plenum. Put it the other way up and a
        50 mm deck would cost 0.4 m2 of a 3.6 m2 plenum, because at this height
        we are squeezing into the eave.
        """
        made = []
        if self.plenumZ <= 0:
            return made
        s = float(self.g['scale'])
        hx = [v * s for v in self.g['hac']['x']]
        hy = [v * s for v in self.g['hac']['y']]
        dt = self.g['hac']['door_t'] * s
        xw = self.ends['W']['body'][1]          # west bulkhead plane
        xe = self.ends['E']['body'][0]          # east bulkhead plane
        z0, z1 = self.plenumZ - self.deckT, self.plenumZ

        # Deck over the whole cold side, open only above the hot aisle.
        slabs = [('deck_s', xw, xe, self.y0, hy[0]),
                 ('deck_n', xw, xe, hy[1], self.y1),
                 ('deck_w', xw, hx[0], hy[0], hy[1]),
                 ('deck_e', hx[1], xe, hy[0], hy[1])]
        text = ''.join(box_solid(n, a, b, c, d, z0, z1)
                       for n, a, b, c, d in slabs if b > a and d > c)
        self.write('constant/triSurface/plenum_floor.stl', text)
        made.append(('plenum_floor.stl', 'plenumfloor'))

        if self.sealPodEnds:
            # Close the baffled channel ends from the rack tops up to the deck,
            # so exhaust has to rise into the plenum instead of spilling out of
            # the pod ends into the cold aisles.
            rz = self.racks[0]['z1']
            text = (box_solid('podend_w', hx[0] - dt, hx[0], hy[0], hy[1], rz, z0)
                    + box_solid('podend_e', hx[1], hx[1] + dt, hy[0], hy[1], rz, z0))
            self.write('constant/triSurface/pod_ends.stl', text)
            made.append(('pod_ends.stl', 'podends'))
        return made

    def raise_cross_heads(self):
        """Lift the service-run cross-heads clear of the rack intake faces.

        The export keeps three 200 x 250 mm cross-heads whose underside sits at
        1.810 m - 190 mm BELOW the 2.0 m rack tops - and about 250 mm in front of
        the intake plane. Each is a bluff body parked in the intake path, and the
        three racks they cross carry the three hottest faces in the hall. This
        rewrites them to a stated clearance above the rack tops so the fix can be
        tested; the CAD needs the same change.
        """
        src = os.path.join(self.tri, 'gantry.stl')
        clear = float(self.p.get('crossHeadClearance', 0.0))
        if clear <= 0 or not os.path.exists(src):
            return 'gantry.stl', 0

        tris, cur, head = [], [], None
        for line in open(src, errors='replace'):
            t = line.strip()
            if t.startswith('solid'):
                head = t
            elif t.startswith('vertex'):
                cur.append([float(v) for v in t.split()[1:4]])
                if len(cur) == 3:
                    tris.append(cur); cur = []
        rz = self.racks[0]['z1']

        # cluster the sub-rack-height triangles in x to find the members
        pts = sorted({round(v[0], 3) for tr in tris
                      for v in tr if min(w[2] for w in tr) < rz})
        if not pts:
            return 'gantry.stl', 0
        # Build fresh lists: appending `run` and then clearing it aliases every
        # group to the same emptied list, which silently found one member instead
        # of three.
        groups, run = [], [pts[0]]
        for x in pts[1:]:
            if x - run[-1] < 0.5:
                run.append(x)
            else:
                groups.append(run)
                run = [x]
        groups.append(run)
        spans = [(min(g), max(g)) for g in groups if g]

        # a member's own triangles are the ones inside its x span and below the
        # next tier of services; anything higher is busway or tray and stays put
        moved = 0
        for tr in tris:
            for x0, x1 in spans:
                if all(x0 - 1e-6 <= v[0] <= x1 + 1e-6 for v in tr) \
                        and max(v[2] for v in tr) <= rz + 0.15:
                    dz = (rz + clear) - min(v[2] for v in tr)
                    if dz > 0:
                        for v in tr:
                            v[2] += dz
                        moved += 1
                    break
        out = [(head or 'solid gantry') + '\n']
        for tr in tris:
            out.append('  facet normal 0 0 0\n    outer loop\n')
            for v in tr:
                out.append('      vertex %.6f %.6f %.6f\n' % tuple(v))
            out.append('    endloop\n  endfacet\n')
        out.append('endsolid gantry\n')
        self.write('constant/triSurface/gantry_raised.stl', ''.join(out))
        return 'gantry_raised.stl', moved

    def plenum_area(self):
        """Cross-section available for flow along the hall, above the deck."""
        W = self.y1 - self.y0
        z = self.plenumZ
        if z >= self.apex:
            return 0.0
        if z <= self.eave:
            return W * (self.eave - z) + 0.5 * W * (self.apex - self.eave)
        frac = (self.apex - z) / (self.apex - self.eave)
        return 0.5 * (W * frac) * (self.apex - z)

    def blockMeshDict(self):
        t = [HEADER, foam('dictionary', 'blockMeshDict'), '\nscale 1;\n\nvertices\n(\n']
        for z in (self.z0, self.z1):
            for x, y in ((self.x0, self.y0), (self.x1, self.y0),
                         (self.x1, self.y1), (self.x0, self.y1)):
                t.append('    (%.6f %.6f %.6f)\n' % (x, y, z))
        t.append(');\n\nblocks\n(\n    hex (0 1 2 3 4 5 6 7) (%d %d %d) simpleGrading (1 1 1)\n);\n'
                 % (self.nx, self.ny, self.nz))
        t.append('\nedges ();\n\nboundary\n(\n')
        faces = OrderedDict()
        faces['floor'] = '(0 3 2 1)'
        faces['ceiling'] = '(4 5 6 7)'
        faces['wallW'] = '(0 4 7 3)'
        faces['wallE'] = '(1 2 6 5)'
        faces['wallS'] = '(0 1 5 4)'
        faces['wallN'] = '(3 7 6 2)'
        for n, f in faces.items():
            t.append('    %s { type wall; faces ( %s ); }\n' % (n, f))
        t.append(');\n\nmergePatchPairs ();\n')
        return ''.join(t)

    def snappyHexMeshDict(self):
        lvl = self.i('thinPlateLevel')
        surf = [('roof.stl', 'roof', 0)]
        for end in ('w', 'e'):
            surf.append(('fanwall_%s_body.stl' % end, 'fanwall%s' % end.upper(), 0))
        surf.append(('bulkheads_%s.stl' % self.p['bulkhead'], 'bulkheads', lvl))
        surf.append(('hac.stl', 'hac', lvl))
        if self.p.get('gantry', '1') != '0':
            surf.append((self._gantry_file, 'gantry', lvl))
        for fn, nm in self._extra:
            surf.append((fn, nm, lvl))

        t = [HEADER, foam('dictionary', 'snappyHexMeshDict'),
             '\ncastellatedMesh true;\nsnap true;\naddLayers false;\n\ngeometry\n{\n']
        for fn, nm, _ in surf:
            t.append('    %s { type triSurfaceMesh; name %s; }\n' % (fn, nm))
        t.append('}\n\ncastellatedMeshControls\n{\n')
        t.append('    maxLocalCells 30000000;\n    maxGlobalCells 60000000;\n'
                 '    minRefinementCells 0;\n    nCellsBetweenLevels 2;\n'
                 '    maxLoadUnbalance 0.10;\n    resolveFeatureAngle 45;\n'
                 '    allowFreeStandingZoneFaces true;\n    features ();\n\n'
                 '    refinementSurfaces\n    {\n')
        for _, nm, l in surf:
            t.append('        %s { level (%d %d); patchInfo { type wall; } }\n' % (nm, l, l))
        t.append('    }\n\n    refinementRegions {}\n\n')
        # A point in the south cold aisle, deliberately off every cell face.
        px = self.x0 + 0.5 * (self.x1 - self.x0) + 0.013
        py = self.y0 + 0.5 * (self.racks[0]['intake_y'] - self.y0) + 0.017
        pz = 1.0 + 0.013
        t.append('    locationInMesh (%.4f %.4f %.4f);\n}\n' % (px, py, pz))
        t.append('\nsnapControls\n{\n    nSmoothPatch 3;\n    tolerance 2.0;\n'
                 '    nSolveIter 50;\n    nRelaxIter 5;\n    nFeatureSnapIter 10;\n'
                 '    implicitFeatureSnap true;\n    explicitFeatureSnap false;\n'
                 '    multiRegionFeatureSnap false;\n}\n')
        t.append('\naddLayersControls\n{\n    relativeSizes true;\n    layers {}\n'
                 '    expansionRatio 1.0;\n    finalLayerThickness 0.3;\n'
                 '    minThickness 0.1;\n    nGrow 0;\n    featureAngle 60;\n'
                 '    nRelaxIter 3;\n    nSmoothSurfaceNormals 1;\n'
                 '    nSmoothNormals 3;\n    nSmoothThickness 10;\n'
                 '    maxFaceThicknessRatio 0.5;\n    maxThicknessToMedialRatio 0.3;\n'
                 '    minMedialAxisAngle 90;\n    nBufferCellsNoExtrude 0;\n'
                 '    nLayerIter 50;\n}\n')
        # the shipped meshQualityDict has no errorReduction / nSmoothScale, and
        # snappyHexMesh reads both unconditionally
        t.append('\nmeshQualityControls\n{\n    #includeEtc "caseDicts/meshQualityDict"\n'
                 '    nSmoothScale 4;\n    errorReduction 0.75;\n'
                 '    relaxed { maxNonOrtho 75; }\n}\n')
        t.append('\nwriteFlags ( );\nmergeTolerance 1e-6;\n')
        return ''.join(t)

    def topoSetDict_patches(self):
        """Split the fan wall discharge and return faces off the body patches."""
        ex, ey, ez = 0.4 * self.dx, 0.4 * self.dy, 0.4 * self.dz
        t = [HEADER, foam('dictionary', 'topoSetDict'), '\nactions\n(\n']
        for name, end, m in self.patches():
            e = self.ends[end]
            xc = e['supply_x'] if name.startswith('supply') else e['intake_x']
            zlo, zhi = self.module_z[m - 1]
            t.append('    { name %sFaces; type faceSet; action new; source patchToFace; patch fanwall%s; }\n'
                     % (name, end))
            t.append('    { name %sFaces; type faceSet; action subset; source boxToFace; '
                     'box (%.5f %.5f %.5f) (%.5f %.5f %.5f); }\n'
                     % (name, xc - ex, self.fw_y[0] + ey, zlo + ez,
                        xc + ex, self.fw_y[1] - ey, zhi - ez))
        t.append(');\n')
        return ''.join(t)

    def createPatchDict(self):
        t = [HEADER, foam('dictionary', 'createPatchDict'), '\npointSync false;\n\npatches\n(\n']
        for name, _, _ in self.patches():
            t.append('    { name %s; patchInfo { type patch; } constructFrom set; set %sFaces; }\n'
                     % (name, name))
        t.append(');\n')
        return ''.join(t)

    def topoSetDict_racks(self):
        """Rack cell zones and oriented intake face zones.

        Racks stay as fluid cells rather than solid blockages: the heat and the
        server fans are volume sources, so each rack heats whatever air it
        actually ingests. That is the whole point of the study - a solid rack
        with a fixed exhaust temperature would answer a different question.
        """
        ex, ey, ez = 0.2 * self.dx, 0.2 * self.dy, 0.2 * self.dz
        t = [HEADER, foam('dictionary', 'topoSetDict'), '\nactions\n(\n']
        for r in self.racks:
            tag = r['tag']
            t.append('    { name rackCells_%s; type cellSet; action new; source boxToCell; '
                     'box (%.5f %.5f %.5f) (%.5f %.5f %.5f); }\n'
                     % (tag, r['x0'] + ex, r['y0'] + ey, r['z0'] - ez,
                        r['x1'] - ex, r['y1'] - ey, r['z1'] - ez))
            t.append('    { name rack_%s; type cellZoneSet; action new; source setToCellZone; '
                     'set rackCells_%s; }\n' % (tag, tag))
            iy = r['intake_y']
            t.append('    { name inletFaces_%s; type faceSet; action new; source boxToFace; '
                     'box (%.5f %.5f %.5f) (%.5f %.5f %.5f); }\n'
                     % (tag, r['x0'] + ex, iy - ey, r['z0'] - ez,
                        r['x1'] - ex, iy + ey, r['z1'] - ez))
            # flip true orients the zone normal *into* the rack, so a positive
            # phi sum is air being drawn in. Same convention as case-hall.
            t.append('    { name inlet_%s; type faceZoneSet; action new; source setsToFaceZone; '
                     'faceSet inletFaces_%s; cellSet rackCells_%s; flip true; }\n'
                     % (tag, tag, tag))
            # Split the face into height bands. A whole-face average hides
            # stratification: the end racks run 9 K hotter at one part of the
            # face than the average suggests, and the average cannot say where.
            nb = self.bands
            for b in range(nb):
                zb0 = r['z0'] + (r['z1'] - r['z0']) * b / float(nb)
                zb1 = r['z0'] + (r['z1'] - r['z0']) * (b + 1) / float(nb)
                t.append('    { name inletFaces_%s_b%d; type faceSet; action new; '
                         'source boxToFace; box (%.5f %.5f %.5f) (%.5f %.5f %.5f); }\n'
                         % (tag, b + 1, r['x0'] + ex, iy - ey, zb0 + ez,
                            r['x1'] - ex, iy + ey, zb1 - ez))
                t.append('    { name inlet_%s_b%d; type faceZoneSet; action new; '
                         'source setsToFaceZone; faceSet inletFaces_%s_b%d; '
                         'cellSet rackCells_%s; flip true; }\n'
                         % (tag, b + 1, tag, b + 1, tag))
        t.append(');\n')
        return ''.join(t)

    def topoSetDict_baffles(self):
        """Close the rack tops and the outboard row ends.

        The racks are fluid cellZones so their heat and fans can act on the air
        they actually ingest. The cost is that a cellZone has no walls: without
        these baffles a rack can draw air in over its top, bypassing the intake
        face that every metric is measured on. case-hall had rack-top baffles;
        they were lost when this case moved to snappyHexMesh and dropped
        createBaffles, and the symptom was the top height band drawing a third
        less flow than the other three.
        """
        ex, ey, ez = 0.2 * self.dx, 0.2 * self.dy, 0.2 * self.dz
        t = [HEADER, foam('dictionary', 'topoSetDict'), '\nactions\n(\n']
        first = True
        for row in ('A', 'B'):
            rs = sorted([r for r in self.racks if r['row'] == row],
                        key=lambda r: r['x0'])
            if not rs:
                continue
            y0, y1, z1 = rs[0]['y0'], rs[0]['y1'], rs[0]['z1']
            # snap to the faces that really bound the cell zones
            xw, xe_ = self._zone_faces(rs[0]['x0'] + ex, rs[-1]['x1'] - ex, self.dx)
            _, ztop = self._zone_faces(z1 - ez - 10 * self.dz, z1 - ez, self.dz)
            act = 'new' if first else 'add'
            # rack tops, one box for the whole row
            t.append('    { name rackShellFaces; type faceSet; action %s; source boxToFace; '
                     'box (%.5f %.5f %.5f) (%.5f %.5f %.5f); }\n'
                     % (act, xw + ex, y0 + ey, ztop - ez, xe_ - ex, y1 - ey, ztop + ez))
            first = False
            # outboard row ends - these bound the four racks that are failing
            for xf in (xw, xe_):
                t.append('    { name rackShellFaces; type faceSet; action add; '
                         'source boxToFace; box (%.5f %.5f %.5f) (%.5f %.5f %.5f); }\n'
                         % (xf - ex, y0 + ey, -ez, xf + ex, y1 - ey, ztop - ez))
        t.append('    { name rackShell; type faceZoneSet; action new; source setToFaceZone; '
                 'faceSet rackShellFaces; }\n')
        t.append(');\n')
        return ''.join(t)

    def createBafflesDict(self):
        return (HEADER + foam('dictionary', 'createBafflesDict')
                + '\ninternalFacesOnly true;\n\nbaffles\n{\n    rackShell\n    {\n'
                  '        type faceZone;\n        zoneName rackShell;\n'
                  '        patches\n        {\n'
                  '            master { name rackShell; type wall; }\n'
                  '            slave  { name rackShell_slave; type wall; }\n'
                  '        }\n    }\n}\n')

    def fvOptions(self):
        C = self.f('fanStiffness')
        t = [HEADER, foam('dictionary', 'fvOptions'),
             '// %d racks, %.1f kW air total.\n' % (len(self.racks), self.load_kW),
             '// Server fans are held at the velocity that carries each rack\'s own\n'
             '// load at dT = %.1f K, so a %.0f kW rack does not move %.0f kW of air.\n'
             % (self.dT, max(r['kW'] for r in self.racks),
                min(r['kW'] for r in self.racks))]
        # Startup guards. On a cut mesh the first few iterations can drive h
        # negative near a skewed cell before the field organises itself, which
        # kills the run outright. Neither bound is physically reachable here
        # (supply is 301 K, the slot runs at a few m/s), so if either one is
        # still clipping at convergence the result is not to be trusted -
        # plot_au01.py checks the final field against them.
        t.append('\nlimitT\n{\n    type limitTemperature; active true;\n'
                 '    selectionMode all; min 273; max 373;\n}\n')
        t.append('\nlimitU\n{\n    type limitVelocity; active true;\n'
                 '    selectionMode all; max 25;\n}\n')
        for r in self.racks:
            tag = r['tag']
            mdot = r['kW'] * 1000.0 / (CP * self.dT)
            u = mdot / (self.rho * r['area']) * r['dir']
            t.append('\nrackHeat_%s\n{\n    type scalarSemiImplicitSource; '
                     'selectionMode cellZone; cellZone rack_%s;\n'
                     '    volumeMode absolute;\n    sources { h (%.1f 0); }\n}\n'
                     % (tag, tag, r['kW'] * 1000.0))
            t.append('\nrackFans_%s\n{\n    type vectorSemiImplicitSource; '
                     'selectionMode cellZone; cellZone rack_%s;\n'
                     '    volumeMode specific;\n    sources { U ((0 %.4f 0) -%g); }\n}\n'
                     % (tag, tag, C * u, C))
        return ''.join(t)

    def functions(self):
        n = self.i('functionInterval')
        t = [HEADER]
        for r in self.racks:
            tag = r['tag']
            t.append('\nr%s_inletT\n{\n    type surfaceFieldValue; libs (fieldFunctionObjects);\n'
                     '    regionType faceZone; name inlet_%s;\n'
                     '    operation areaAverage; fields (T);\n'
                     '    writeFields false; writeControl timeStep; writeInterval %d; log false;\n}\n'
                     % (tag, tag, n))
            t.append('r%s_inletTmax { $r%s_inletT; operation max; }\n' % (tag, tag))
            t.append('r%s_flow      { $r%s_inletT; operation sum; fields (phi); }\n' % (tag, tag))
            for b in range(1, self.bands + 1):
                t.append('r%s_b%d_T    { $r%s_inletT; name inlet_%s_b%d; }\n'
                         % (tag, b, tag, tag, b))
                t.append('r%s_b%d_flow { $r%s_inletT; name inlet_%s_b%d; '
                         'operation sum; fields (phi); }\n' % (tag, b, tag, tag, b))
        for name, _, _ in self.patches():
            t.append('\n%s_flow\n{\n    type surfaceFieldValue; libs (fieldFunctionObjects);\n'
                     '    regionType patch; name %s;\n'
                     '    operation sum; fields (phi);\n'
                     '    writeArea true;\n'
                     '    writeFields false; writeControl timeStep; writeInterval %d; log false;\n}\n'
                     % (name, name, n))
            t.append('%s_T { $%s_flow; operation areaAverage; fields (T); }\n' % (name, name))
            # p_rgh at the discharge minus p_rgh at the return IS the external
            # static the fan has to provide. That makes the 70 Pa ESP budget a
            # measured quantity rather than a hand calculation.
            t.append('%s_p { $%s_flow; operation areaAverage; fields (p_rgh); }\n'
                     % (name, name))
        t.append('\nroomT\n{\n    type volFieldValue; libs (fieldFunctionObjects);\n'
                 '    regionType all; operation max; fields (T);\n'
                 '    writeFields false; writeControl timeStep; writeInterval %d; log false;\n}\n' % n)
        t.append('roomTmean { $roomT; operation volAverage; }\n')
        if self.transient:
            t.append('\naverage\n{\n    type fieldAverage; libs (fieldFunctionObjects);\n'
                     '    writeControl writeTime;\n    timeStart %g;\n    fields\n    (\n'
                     '        T { mean on; prime2Mean off; base time; }\n'
                     '        U { mean on; prime2Mean off; base time; }\n'
                     '    );\n}\n' % self.f('averageFrom'))
        return ''.join(t)

    def controlDict(self):
        t = [HEADER, foam('dictionary', 'controlDict'), '\n']
        t.append('application     %s;\nstartFrom       startTime;\n'
                 'startTime       0;\nstopAt          endTime;\n' % self.solver)
        if self.transient:
            t.append('endTime         %g;\ndeltaT          0.002;\n'
                     'writeControl    runTime;\nwriteInterval   %g;\n'
                     'adjustTimeStep  yes;\nmaxCo           %g;\nmaxDeltaT       %g;\n'
                     % (self.f('endTime'), self.f('writeEvery'),
                        self.f('maxCo'), self.f('maxDeltaT')))
        else:
            t.append('endTime         %d;\ndeltaT          1;\nwriteControl    timeStep;\n'
                     'writeInterval   %d;\n'
                     % (self.i('iterations'), self.i('writeInterval')))
        t.append('purgeWrite      2;\nwriteFormat     binary;\nwritePrecision  8;\n'
                 'writeCompression off;\ntimeFormat      general;\ntimePrecision   6;\n'
                 'runTimeModifiable false;\n\nfunctions\n{\n    #include "au01Functions"\n}\n')
        return ''.join(t)

    def fvSchemes(self):
        """Schemes tolerant of a cut mesh; ddt switches with the solver.

        Deliberately not case-hall's. That case ran on an orthogonal blockMesh,
        so plain Gauss linear gradients and a corrected laplacian were safe. This
        mesh is cut around the gantry, the gable and 100 mm plates and carries
        skewed cells there; unlimited gradients diverge within ten iterations.
        """
        ddt = 'Euler' if self.transient else 'steadyState'
        t = [HEADER, foam('dictionary', 'fvSchemes'),
             '\nddtSchemes\n{\n    default         %s;\n}\n' % ddt,
             '\ngradSchemes\n{\n    default         cellLimited Gauss linear 1;\n}\n',
             '\ndivSchemes\n{\n    default         none;\n\n']
        # 'bounded' subtracts the continuity error and only belongs in a steady run
        b = '' if self.transient else 'bounded '
        for term, sch in (('div(phi,U)', 'limitedLinearV 1'),
                          ('div(phi,K)', 'limitedLinear 1'),
                          ('div(phi,h)', 'limitedLinear 1'),
                          ('div(phi,e)', 'limitedLinear 1'),
                          ('div(phi,Ekp)', 'limitedLinear 1'),
                          ('div(phi,k)', 'limitedLinear 1'),
                          ('div(phi,omega)', 'limitedLinear 1'),
                          ('div(phid,p)', 'limitedLinear 1')):
            t.append('    %-16s %sGauss %s;\n' % (term, b, sch))
        t.append('    div(((rho*nuEff)*dev2(T(grad(U))))) Gauss linear;\n}\n')
        t.append('\nlaplacianSchemes\n{\n    default         Gauss linear limited corrected 0.33;\n}\n')
        t.append('\ninterpolationSchemes\n{\n    default         linear;\n}\n')
        t.append('\nsnGradSchemes\n{\n    default         limited corrected 0.33;\n}\n')
        t.append('\nwallDist\n{\n    method          meshWave;\n}\n')
        return ''.join(t)

    def fvSolution(self):
        """GAMG is tuned explicitly: on this cut mesh the defaults coarsen far
        enough to hit a degenerate level and die inside GAMGSolver::scale with a
        floating point exception that looks nothing like a physics problem."""
        gamg = ('        solver          GAMG;\n        smoother        GaussSeidel;\n'
                '        tolerance       1e-7;\n        relTol          0.01;\n'
                '        cacheAgglomeration true;\n        agglomerator    faceAreaPair;\n'
                '        nCellsInCoarsestLevel 500;\n        mergeLevels     1;\n'
                '        nPreSweeps      0;\n        nPostSweeps     2;\n')
        t = [HEADER, foam('dictionary', 'fvSolution'), '\nsolvers\n{\n']
        t.append('    p_rgh\n    {\n%s    }\n' % gamg)
        if self.transient:
            t.append('\n    p_rghFinal\n    {\n        $p_rgh;\n        relTol          0;\n    }\n')
        t.append('\n    "(U|h|e|k|omega)"\n    {\n        solver          PBiCGStab;\n'
                 '        preconditioner  DILU;\n        tolerance       1e-7;\n'
                 '        relTol          0.1;\n    }\n')
        if self.transient:
            t.append('\n    "(U|h|e|k|omega)Final"\n    {\n        $U;\n'
                     '        relTol          0;\n    }\n')
            t.append('\n    "(rho|rhoFinal)"\n    {\n        solver          PCG;\n'
                     '        preconditioner  DIC;\n        tolerance       1e-7;\n'
                     '        relTol          0;\n    }\n')
        t.append('}\n')
        if self.transient:
            # Every boundary prescribes a flow rate, so there is no pressure
            # outlet anywhere and p_rgh needs an explicit reference.
            t.append('\nPIMPLE\n{\n    momentumPredictor yes;\n    nOuterCorrectors 2;\n'
                     '    nCorrectors     1;\n    nNonOrthogonalCorrectors 0;\n'
                     '    pRefCell        0;\n    pRefValue       %g;\n}\n' % P_ATM)
            t.append('\nrelaxationFactors\n{\n    fields\n    {\n        p_rgh 0.7;\n'
                     '        "p_rghFinal" 1;\n    }\n    equations\n    {\n'
                     '        "(U|h|k|omega)" 0.8;\n        ".*Final" 1;\n    }\n}\n')
        else:
            t.append('\nSIMPLE\n{\n    nNonOrthogonalCorrectors 0;\n    pRefCell        0;\n'
                     '    pRefValue       %g;\n\n    residualControl\n    {\n'
                     '        p_rgh           1e-4;\n        U               1e-4;\n'
                     '        h               1e-4;\n        "(k|omega)"     1e-3;\n'
                     '    }\n}\n' % P_ATM)
            t.append('\nrelaxationFactors\n{\n    fields\n    {\n        rho             1.0;\n'
                     '        p_rgh           0.3;\n    }\n    equations\n    {\n'
                     '        U               0.5;\n        h               0.4;\n'
                     '        "(k|omega)"     0.4;\n    }\n}\n')
        return ''.join(t)

    def decomposeParDict(self):
        return (HEADER + foam('dictionary', 'decomposeParDict')
                + '\nnumberOfSubdomains %d;\nmethod scotch;\n' % self.i('numberOfSubdomains'))

    def slices(self):
        yc = 0.5 * (self.y0 + self.y1)
        xc = 0.5 * (self.racks[0]['x0'] + self.racks[-1]['x1'])
        t = [HEADER, foam('dictionary', 'slices'),
             '\ntype surfaces;\nlibs (sampling);\nwriteControl onEnd;\n'
             'surfaceFormat raw;\ninterpolationScheme cellPoint;\nfields (T U);\n\nsurfaces\n{\n']
        for nm, pt, nrm in (('rack_mid', (xc, yc, 1.0), (0, 0, 1)),
                            ('aisle_long', (xc, yc, 1.0), (0, 1, 0)),
                            ('pod_cross', (xc, yc, 1.0), (1, 0, 0))):
            t.append('    %s\n    {\n        type plane; planeType pointAndNormal;\n'
                     '        pointAndNormalDict { point (%.4f %.4f %.4f); normal (%d %d %d); }\n'
                     '        interpolate true;\n    }\n' % ((nm,) + pt + nrm))
        t.append('}\n')
        return ''.join(t)

    # ---- fields --------------------------------------------------------

    def field(self, name, cls, dims, internal, bcs, wall):
        t = [HEADER, foam(cls, name), '\ndimensions      [%s];\n' % dims,
             '\ninternalField   uniform %s;\n\nboundaryField\n{\n' % internal]
        for pname, body in bcs:
            t.append('    %s\n    {\n%s    }\n\n' % (pname, body))
        t.append('    "(floor|ceiling|wall.*|roof.*|fanwall.*|bulkheads.*|hac.*|gantry.*|plenumfloor.*|podends.*|rackShell.*)"\n'
                 '    {\n%s    }\n\n' % wall)
        # The mesh is only ever built decomposed, so restore0Dir -processor
        # copies these files straight into processor*/0 and the inter-processor
        # patches need an entry of their own. Matches nothing when serial.
        t.append('    "procBoundary.*"\n    {\n        type            processor;\n'
                 '        value           uniform %s;\n    }\n}\n' % internal)
        return ''.join(t)

    def fields(self):
        Tret = self.Tsup + self.dT
        out = {}

        # A stopped module is modelled as blanked off: no flow either way. A
        # failed unit whose fans free-wheel would let air short circuit through
        # it, which is a separate and worse case.
        Ubcs, Tbcs, prghbcs = [], [], []
        for name, end, m in self.patches():
            e = self.ends[end]
            if not self.live(name):
                Ubcs.append((name, '        type            noSlip;\n'))
                Tbcs.append((name, '        type            zeroGradient;\n'))
                prghbcs.append((name, '        type            fixedFluxPressure;\n'
                                      '        value           uniform %g;\n' % P_ATM))
                continue
            if name.startswith('supply'):
                u = self.supply_U * e['sign']
                # Prescribe MASS flow, and prescribe the same mass at this
                # module's own return. A 40L1 is a closed loop - its fans pull
                # through its own coil - so it must pass equal mass in and out.
                # Leaving the return as a pressure outlet only balances mass
                # across a whole end, and the solver then drew 37 kg/s through
                # the lower module against 5 through the upper one. That was an
                # artefact of the boundary condition, not a starved module.
                Ubcs.append((name, '        type            flowRateInletVelocity;\n'
                                   '        massFlowRate    constant %.5f;\n'
                                   '        rhoInlet        %.5f;\n'
                                   '        value           uniform (%.4f 0 0);\n'
                                   % (self.mod_mdot, self.rho, u)))
                Tbcs.append((name, '        type            fixedValue;\n'
                                   '        value           uniform %.2f;\n' % self.Tsup))
            else:
                Ubcs.append((name, '        type            flowRateOutletVelocity;\n'
                                   '        massFlowRate    constant %.5f;\n'
                                   '        rhoOutlet       %.5f;\n'
                                   '        value           uniform (0 0 0);\n'
                                   % (self.mod_mdot, self.rho)))
                Tbcs.append((name, '        type            inletOutlet;\n'
                                   '        inletValue      uniform %.2f;\n'
                                   '        value           uniform %.2f;\n' % (Tret, Tret)))
            # Every boundary now prescribes flow, so there is no pressure outlet
            # and p_rgh is pinned by pRefCell/pRefValue instead. Mass in equals
            # mass out by construction, which is what keeps that solvable.
            prghbcs.append((name, '        type            fixedFluxPressure;\n'
                                  '        value           uniform %g;\n' % P_ATM))

        out['U'] = self.field('U', 'volVectorField', '0 1 -1 0 0 0 0', '(0 0 0)',
                              Ubcs, '        type            noSlip;\n')
        out['T'] = self.field('T', 'volScalarField', '0 0 0 1 0 0 0', '%.2f' % self.Tsup,
                              Tbcs, '        type            zeroGradient;\n')
        out['p_rgh'] = self.field('p_rgh', 'volScalarField', '1 -1 -2 0 0 0 0', '%g' % P_ATM,
                                  prghbcs, '        type            fixedFluxPressure;\n'
                                           '        value           uniform %g;\n' % P_ATM)
        out['p'] = self.field('p', 'volScalarField', '1 -1 -2 0 0 0 0', '%g' % P_ATM,
                              [(n, '        type            calculated;\n'
                                   '        value           uniform %g;\n' % P_ATM)
                               for n, _, _ in self.patches()],
                              '        type            calculated;\n'
                              '        value           uniform %g;\n' % P_ATM)

        # k-omega inlet values from a 5 % turbulence intensity at the discharge.
        I, L = 0.05, 0.1 * (self.fw_y[1] - self.fw_y[0])
        k = 1.5 * (self.supply_U * I) ** 2
        omega = math.sqrt(k) / (0.09 ** 0.25 * L)
        nut = 0.09 * k / omega
        for nm, cls, dims, val, wall in (
                ('k', 'volScalarField', '0 2 -2 0 0 0 0', k,
                 '        type            kqRWallFunction;\n        value           uniform %.6g;\n' % k),
                ('omega', 'volScalarField', '0 0 -1 0 0 0 0', omega,
                 '        type            omegaWallFunction;\n        value           uniform %.6g;\n' % omega),
                ('nut', 'volScalarField', '0 2 -1 0 0 0 0', nut,
                 '        type            nutkWallFunction;\n        value           uniform 0;\n'),
                ('alphat', 'volScalarField', '1 -1 -1 0 0 0 0', 0.0,
                 '        type            compressible::alphatWallFunction;\n'
                 '        Prt             0.85;\n        value           uniform 0;\n')):
            bcs = []
            for n, _, _ in self.patches():
                if nm in ('nut', 'alphat'):
                    bcs.append((n, '        type            calculated;\n'
                                   '        value           uniform %.6g;\n' % val))
                elif n.startswith('supply') and self.live(n):
                    bcs.append((n, '        type            fixedValue;\n'
                                   '        value           uniform %.6g;\n' % val))
                else:
                    bcs.append((n, '        type            inletOutlet;\n'
                                   '        inletValue      uniform %.6g;\n'
                                   '        value           uniform %.6g;\n' % (val, val)))
            out[nm] = self.field(nm, cls, dims, '%.6g' % val, bcs, wall)
        return out

    # ---- checks and report ---------------------------------------------

    def checks(self):
        """Fail loudly rather than produce a plausible wrong mesh."""
        c = self.f('cellSize')
        if abs(self.dz - c) > 1e-12:
            raise SystemExit('dz %.6f != cellSize %.6f' % (self.dz, c))
        if self.z1 < self.apex - 1e-9:
            raise SystemExit('box top %.4f is below the apex %.4f' % (self.z1, self.apex))

        def on_face(v, d, label):
            off = abs(v - round(v / d) * d)
            if off > 1e-3:                      # 1 mm; below that it is STL noise
                warn.append('%s = %.4f m is %.0f mm off a cell face'
                            % (label, v, off * 1000))
        warn = []
        for r in self.racks[:1]:
            on_face(r['y0'], self.dy, 'rack row face y')
            on_face(r['z1'], self.dz, 'rack top z')
        on_face(self.fw_top, self.dz, 'fan wall top z')
        on_face(self.fw_split, self.dz, 'module split z')

        cols = [r['ncx'] for r in self.racks]
        if min(cols) < 1:
            raise SystemExit('a rack zone would capture no cells at cellSize %.3f' % c)
        return warn, cols

    def report(self, warn, cols):
        nmod = len(self.ends) * self.modules
        live = nmod - len(self.off)
        L = ['  room            %.3f x %.3f m, eave %.3f, apex %.3f (gable, no plenum)'
             % (self.x1 - self.x0, self.y1 - self.y0, self.eave, self.apex),
             '  background mesh %d x %d x %d = %s cells  (%.1f x %.1f x %.1f mm)'
             % (self.nx, self.ny, self.nz, '{:,}'.format(self.nx * self.ny * self.nz),
                self.dx * 1000, self.dy * 1000, self.dz * 1000),
             '  bulkhead        %s   gantry %s   thin-plate refinement level %d'
             % (self.p['bulkhead'], 'in' if self.p.get('gantry', '1') != '0' else 'OUT',
                self.i('thinPlateLevel')),
             '  racks           %d, %.1f kW air  (%s)'
             % (len(self.racks), self.load_kW,
                ', '.join('%dx%.0f kW' % (sum(1 for r in self.racks if r['kW'] == v), v)
                          for v in sorted({r['kW'] for r in self.racks}, reverse=True))),
             '                  %s cell columns per rack; fans sized on the '
             'measured zone area so mass flow per rack is exact'
             % (str(cols[0]) if len(set(cols)) == 1
                else '%d-%d' % (min(cols), max(cols))),
             '  fan walls       %d of %d modules live%s'
             % (live, nmod, '' if not self.off else '  (OFF: %s)' % ' '.join(sorted(self.off))),
             '  capacity        %.1f kW vs %.1f kW load  -> %.0f %%'
             % (self.cap_kW, self.load_kW, 100.0 * self.cap_kW / self.load_kW),
             '  discharge       %.3f m/s over %.1f m2 per module' % (self.supply_U, self.mod_area),
             '  airflow         supply %.2f kg/s vs demand %.2f kg/s  -> %.3f'
             % (self.supply_kgs, self.demand, self.supply_kgs / self.demand),
             '  supply / return %.1f C / %.1f C at dT %.1f K'
             % (self.Tsup - 273.15, self.Tsup - 273.15 + self.dT, self.dT),
             '  envelope        A2 allowable %.1f C, recommended %.1f C'
             % (self.f('allowableMax_C'), self.f('recommendedMax_C')),
             '  solver          %s' % self.solver
             + ('   %.0f s, averaging from %.0f s, maxCo %.1f'
                % (self.f('endTime'), self.f('averageFrom'), self.f('maxCo'))
                if self.transient else '   %d iterations' % self.i('iterations')),
             '  fan stiffness   %.0f   per-module return coupled to its own supply '
             '(%.2f kg/s each)' % (self.f('fanStiffness'), self.mod_mdot)]
        if self.throttle != 1.0:
            L.append('  throttle        %.0f %% of nameplate  -> supply/demand %.3f'
                     % (100 * self.throttle, self.supply_kgs / self.demand))
        if self._raised:
            L.append('  cross-heads     RAISED: %d facets lifted to %.0f mm above '
                     'the rack tops' % (self._raised,
                                        float(self.p['crossHeadClearance']) * 1000))
        if self.plenumZ > 0:
            A = self.plenum_area()
            rho_r = P_ATM / (R_AIR * (self.Tsup + self.dT))
            v = (self.supply_kgs / rho_r / 2.0) / A if A > 0 else float('inf')
            L.append('  plenum          deck top at %.2f m (%.0f mm thick), '
                     'cross-section %.2f m2' % (self.plenumZ, self.deckT * 1000, A))
            L.append('                  %.2f m/s along the plenum, dynamic head '
                     '%.0f Pa (ESP budget 70 Pa)' % (v, 0.5 * rho_r * v * v))
            L.append('  intake bands    %d per face (%.0f mm each) to expose stratification'
                     % (self.bands, (self.racks[0]['z1'] - self.racks[0]['z0'])
                        / self.bands * 1000))
            L.append('  pod ends        %s' % ('ENCLOSED to the deck'
                                               if self.sealPodEnds else 'open'))
        for w in warn:
            L.append('  NOTE            %s' % w)
        return '\n'.join(L)

    # ---- drive ---------------------------------------------------------

    def build(self):
        warn, cols = self.checks()
        extract_roof(os.path.join(self.tri, 'room_shell.stl'),
                     os.path.join(self.tri, 'roof.stl'))
        self._extra = self.extra_stls()
        self._gantry_file, self._raised = self.raise_cross_heads()
        self.write('system/blockMeshDict', self.blockMeshDict())
        self.write('system/fvSchemes', self.fvSchemes())
        self.write('system/fvSolution', self.fvSolution())
        self.write('system/snappyHexMeshDict', self.snappyHexMeshDict())
        self.write('system/topoSetDict.patches', self.topoSetDict_patches())
        self.write('system/createPatchDict', self.createPatchDict())
        self.write('system/topoSetDict.baffles', self.topoSetDict_baffles())
        self.write('system/createBafflesDict', self.createBafflesDict())
        self.write('system/topoSetDict.racks', self.topoSetDict_racks())
        self.write('system/fvOptions', self.fvOptions())
        self.write('system/au01Functions', self.functions())
        self.write('system/controlDict', self.controlDict())
        self.write('system/decomposeParDict', self.decomposeParDict())
        self.write('system/slices', self.slices())
        for name, text in self.fields().items():
            self.write(os.path.join('0.orig', name), text)
        return self.report(warn, cols)


def main():
    case = sys.argv[1] if len(sys.argv) > 1 else 'case-au01'
    if not os.path.isdir(os.path.join(case, 'system')):
        raise SystemExit('%s does not look like a case directory' % case)
    print(Case(case).build())


if __name__ == '__main__':
    main()
