#!/usr/bin/env python3
"""
Generate the per-cabinet dictionaries for a row of cabinets.

One cell zone, one heat source, one fan source and one set of metrics per
cabinet, so that individual cabinets can carry different loads and be reported
separately. Hand-writing this is untenable beyond about two cabinets.

Reads   case/system/simulationParameters   (geometry, default load)
        case/row_loads.csv    (optional: per-cabinet kW; missing -> all equal)
Writes  case/system/topoSetDict.rowzones
        case/system/fvOptions
        case/system/rowFunctions

Run from run.sh before the mesh is built; safe to re-run.
"""
from __future__ import annotations

import csv
import sys
from pathlib import Path

HEADER = ("// GENERATED by make_row_dicts.py - do not edit.\n"
          "// Change case/system/simulationParameters or case/row_loads.csv instead.\n")

SCALARS = ("nCabinets", "cabinetPitch", "endClearance", "cellSize", "heatLoad",
           "cabinetTargetVelocity", "cabinetFanStiffness", "unitDepth",
           "coldAisleDepth", "cabinetDepth", "cabinetHeight")


def read_params(case: Path) -> dict[str, float]:
    p = {}
    for line in (case / "system" / "simulationParameters").read_text().splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0] in SCALARS:
            try:
                p[parts[0]] = float(parts[1].rstrip(";"))
            except ValueError:
                pass
    missing = set(SCALARS) - set(p)
    if missing:
        raise SystemExit(f"could not read {sorted(missing)} from simulationParameters")
    p["cabinetX0"] = p["unitDepth"] + p["coldAisleDepth"]
    p["cabinetX1"] = p["cabinetX0"] + p["cabinetDepth"]
    return p


def read_loads(case: Path, n: int, default_w: float) -> list[float]:
    """Per-cabinet load in watts. row_loads.csv overrides individual indices."""
    loads = [default_w] * n
    f = case / "row_loads.csv"
    if f.is_file():
        with f.open() as fh:
            for row in csv.DictReader(fh):
                try:
                    i = int(row["index"]); kw = float(row["kW"])
                except (KeyError, ValueError, TypeError):
                    continue
                if 0 <= i < n:
                    loads[i] = kw * 1000.0
                else:
                    print(f"  warning: row_loads.csv index {i} outside 0..{n-1}, ignored")
    return loads


def main() -> int:
    case = Path(sys.argv[1] if len(sys.argv) > 1 else "case")
    p = read_params(case)
    n = int(p["nCabinets"])
    pitch, eps = p["cabinetPitch"], 0.01
    loads = read_loads(case, n, p["heatLoad"])

    # A cabinet's y band. eps is smaller than half a cell, so neighbouring
    # cabinets cannot claim each other's cells.
    def band(i: int) -> tuple[float, float]:
        y0 = p["endClearance"] + i * pitch
        return y0 - eps, y0 + pitch + eps

    x0m, x0p = p["cabinetX0"] - eps, p["cabinetX0"] + eps
    x1p, zp = p["cabinetX1"] + eps, p["cabinetHeight"] + eps

    # ---------------- topoSetDict.rowzones ----------------
    out = [HEADER, "FoamFile { version 2.0; format ascii; class dictionary;",
           "           object topoSetDict; }\n", "actions\n("]
    for i in range(n):
        ya, yb = band(i)
        t = f"{i:02d}"
        out.append(f"""
    // ---- cabinet {t} ----
    {{
        name    serversCells_{t}; type cellSet; action new; source boxToCell;
        box     ({x0m} {ya} {-eps}) ({x1p} {yb} {zp});
    }}
    {{
        name    servers_{t}; type cellZoneSet; action new; source setToCellZone;
        set     serversCells_{t};
    }}
    {{
        name    cabinetInletFaces_{t}; type faceSet; action new; source boxToFace;
        box     ({x0m} {ya} {-eps}) ({x0p} {yb} {zp});
    }}
    {{
        name    cabinetInlet_{t}; type faceZoneSet; action new; source setsToFaceZone;
        faceSet cabinetInletFaces_{t}; cellSet serversCells_{t}; flip true;
    }}""")
    out.append("\n);\n")
    (case / "system" / "topoSetDict.rowzones").write_text("".join(out))

    # ---------------- fvOptions ----------------
    su = p["cabinetFanStiffness"] * p["cabinetTargetVelocity"]
    sp = -p["cabinetFanStiffness"]
    fv = [HEADER, "FoamFile { version 2.0; format ascii; class dictionary;",
          "           object fvOptions; }\n",
          "// One heat source and one fan source per cabinet. volumeMode absolute\n"
          "// means the heat value is that cabinet's total in watts.\n"]
    for i, w in enumerate(loads):
        t = f"{i:02d}"
        fv.append(f"""
serverHeat_{t}
{{
    type scalarSemiImplicitSource; selectionMode cellZone; cellZone servers_{t};
    volumeMode absolute;
    sources {{ h ({w:g} 0); }}
}}

serverFans_{t}
{{
    type vectorSemiImplicitSource; selectionMode cellZone; cellZone servers_{t};
    volumeMode specific;
    sources {{ U (({su:g} 0 0) {sp:g}); }}
}}""")
    (case / "system" / "fvOptions").write_text("".join(fv) + "\n")

    # ---------------- rowFunctions ----------------
    fo = [HEADER]
    for i in range(n):
        t = f"{i:02d}"
        fo.append(f"""
cab{t}_inletT
{{
    type surfaceFieldValue; libs (fieldFunctionObjects);
    regionType faceZone; name cabinetInlet_{t};
    operation areaAverage; fields (T);
    writeFields false; writeControl timeStep; writeInterval 10; log false;
}}
cab{t}_inletTmax {{ $cab{t}_inletT; operation max; }}
cab{t}_flow      {{ $cab{t}_inletT; operation sum; fields (phi); }}""")
    (case / "system" / "rowFunctions").write_text("".join(fo) + "\n")

    tot = sum(loads) / 1000.0
    print(f"  generated for {n} cabinets, {tot:g} kW total "
          f"({', '.join(f'{w/1000:g}' for w in loads)} kW)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
