#!/usr/bin/env python3
"""
Generate the whole OpenFOAM case for the two-row hall from system/hallParameters.

Two rows of racks blowing in opposite directions into a shared contained hot
aisle, with a Schneider FWCV 40L2 fan wall at each end of the hall. 24 rack cell
zones, 48 source terms and ~75 function objects, so every dictionary is written
from Python rather than by hand; the parameter file is the only thing to edit.

    ./make_hall_dicts.py [CASE_DIR]      # default case-hall
"""
from __future__ import annotations

import sys
from pathlib import Path

CP, P_ATM, R_AIR, KELVIN = 1005.0, 101325.0, 287.05, 273.15
GEN = ("// GENERATED by make_hall_dicts.py - do not edit.\n"
       "// Edit system/hallParameters and re-run instead.\n")
FOAM = 'FoamFile {{ version 2.0; format ascii; class dictionary; object {0}; }}\n'


def read_params(case: Path) -> dict:
    p: dict[str, object] = {}
    for line in (case / "system" / "hallParameters").read_text().splitlines():
        line = line.split("#")[0].strip()
        if not line:
            continue
        parts = line.replace("=", " ").split()
        if len(parts) >= 2:
            try:
                p[parts[0]] = float(parts[1])
            except ValueError:
                p[parts[0]] = parts[1]          # string parameter
    return p


class Hall:
    """Every coordinate in the model, derived once from the parameters."""

    def __init__(self, p: dict):
        self.p = p
        c = self.c = p["cellSize"]
        self.eps = c / 4.0          # selection tolerance: < half a cell

        self.n = int(p["nRacksPerRow"])
        self.rowLen = self.n * p["rackPitch"]

        # ---- fan wall bank arrangement -----------------------------------
        # The FWCV is a front-flow unit for service-corridor installation:
        # front discharge, return drawn from BEHIND the unit (brochure p.4).
        # intakeSide rear models that, with a return corridor rearGap deep
        # between the bank and the end wall. intakeSide top keeps the legacy
        # top-of-unit intake fed from the ceiling plenum.
        self.nUnits = int(p.get("nUnitsPerEnd", 1))
        self.unitGap = p.get("unitGap", 0.0)
        # modulesPerUnit splits each unit VERTICALLY into stacked modules
        # (an L2 = 2 stacked L1 modules, each with its own fans and CW valve).
        # supplyZ0/supplyZ1 are then relative to each module's base. With
        # modulesPerUnit 1 they are absolute, i.e. the legacy meaning.
        self.tiers = int(p.get("modulesPerUnit", 1))
        self.moduleH = p["unitHeight"] / self.tiers
        if p["supplyZ1"] > self.moduleH + 1e-9:
            raise SystemExit(
                f"supplyZ1 {p['supplyZ1']:g} exceeds the module height "
                f"{self.moduleH:g} (supplyZ0/Z1 are per-module with "
                f"modulesPerUnit {self.tiers})")
        self.intakeSide = str(p.get("intakeSide", "top"))
        if self.intakeSide not in ("top", "rear"):
            raise SystemExit("intakeSide must be top or rear")
        if self.tiers > 1 and self.intakeSide != "rear":
            raise SystemExit("modulesPerUnit > 1 requires intakeSide rear "
                             "(a top intake cannot serve the lower module)")
        self.rearGap = p.get("rearGap", 0.0) if self.intakeSide == "rear" else 0.0
        if self.intakeSide == "rear" and self.rearGap <= 0:
            raise SystemExit("intakeSide rear needs rearGap > 0")
        off = str(p.get("unitsOff", "")).replace(",", " ").split()
        self.unitsOff = {u.upper() for u in off if u}

        # ---- x: [corridor] unit | clearance | pod | clearance | unit [corridor]
        self.ax0 = self.rearGap
        self.ax1 = self.ax0 + p["unitDepth"]
        self.podX0 = self.ax1 + p["clearance"]
        self.podX1 = self.podX0 + self.rowLen
        self.bx0 = self.podX1 + p["clearance"]
        self.bx1 = self.bx0 + p["unitDepth"]
        self.Lx = self.bx1 + self.rearGap

        # ---- y: aisle | rowA | hot aisle | rowB | aisle
        self.Ly = p["hallWidth"]
        # sideAisle is the nominal cold aisle; the pod is snapped to the cell grid
        # and whatever is left over becomes the far aisle. A 3.9 m pod cannot sit
        # exactly centred in an 8.35 m hall on any practical cell size, so the two
        # aisles differ by up to one cell. Physically irrelevant; numerically it
        # keeps every solid edge on a cell face.
        self.rowAy0 = round(p["sideAisle"] / c) * c
        self.rowAy1 = self.rowAy0 + p["rackDepth"]
        self.hotY0, self.hotY1 = self.rowAy1, self.rowAy1 + p["hotAisleWidth"]
        self.rowBy0, self.rowBy1 = self.hotY1, self.hotY1 + p["rackDepth"]
        self.sideA = self.rowAy0
        self.sideB = self.Ly - self.rowBy1
        if self.sideB <= 0:
            raise SystemExit(
                f"pod ends at {self.rowBy1:.3f} m but hallWidth is {self.Ly:.3f} m "
                f"- no room for the far cold aisle")

        # ---- z
        self.plenum = p["plenumHeight"] > 1e-9
        if not self.plenum and self.intakeSide != "rear":
            raise SystemExit(
                "plenumHeight 0 (open-room return) requires intakeSide rear")
        self.zTop = p["plenumFloorZ"] + p["plenumHeight"]
        self.rackZ = p["rackHeight"]
        self.contZ = p["plenumFloorZ"] - p["containmentGap"]

        # ---- fan wall bank, centred on the hall and snapped to the cell grid.
        # Every solid edge must land on a cell FACE, not a cell centre, or the
        # boxToFace selections silently grab the wrong faces. A 4.0 m unit cannot
        # be exactly centred in a 7.9 m hall on a 100 mm grid, so it is snapped
        # and the offset is reported.
        self.bankWidth = (self.nUnits * p["unitWidth"]
                          + (self.nUnits - 1) * self.unitGap)
        if self.bankWidth > self.Ly + 1e-9:
            raise SystemExit(f"fan wall bank ({self.bankWidth:.2f} m) is wider "
                             f"than the hall ({self.Ly:.2f} m)")
        want = (self.Ly - self.bankWidth) / 2.0
        self.uy0 = round(want / c) * c
        self.uy1 = self.uy0 + self.bankWidth
        self.unitOffset = self.uy0 - want

        def on_grid(v, label):
            if abs(v / c - round(v / c)) > 1e-6:
                raise SystemExit(
                    f"{label} = {v:.4f} m is not a multiple of cellSize {c} m. "
                    f"Solid edges must fall on cell faces; adjust the parameter "
                    f"or reduce cellSize.")

        checks = [(self.rowAy0, "rowA front"), (self.rowAy1, "rowA rear"),
                  (self.hotY0, "hot aisle near"), (self.hotY1, "hot aisle far"),
                  (self.rowBy0, "rowB rear"), (self.rowBy1, "rowB front"),
                  (self.podX0, "pod start"), (self.podX1, "pod end"),
                  (self.rackZ, "rack height"), (p["plenumFloorZ"], "plenum floor"),
                  (self.contZ, "containment top"), (self.uy0, "bank y0"),
                  (self.ax0, "unit A rear face"), (self.ax1, "unit A front face"),
                  (p["unitHeight"], "unit height")]
        for k in range(1, self.nUnits):
            seam = self.uy0 + k * (p["unitWidth"] + self.unitGap)
            checks.append((seam, f"module seam {k}"))
            if self.unitGap:
                checks.append((seam - self.unitGap, f"module seam {k} (gap)"))
        for t in range(self.tiers):
            base = t * self.moduleH
            checks.append((base + p["supplyZ0"], f"tier {t+1} window bottom"))
            checks.append((base + p["supplyZ1"], f"tier {t+1} window top"))
        for v, lbl in checks:
            on_grid(v, lbl)

        self.nx = round(self.Lx / c)
        self.ny = round(self.Ly / c)
        self.nz = round(self.zTop / c)

        # ---- physics
        self.load_W = p["rackLoad_kW"] * 1000.0
        self.Tsup = p["supplyTemp_C"] + KELVIN
        rho_sup = P_ATM / (R_AIR * self.Tsup)
        self.supplyArea = p["unitWidth"] * (p["supplyZ1"] - p["supplyZ0"])
        vdot = p["unitAirflow_m3h"] / 3600.0        # PER MODULE
        self.supplyVel = vdot / self.supplyArea
        self.unitsOn = [u for u in self.all_units() if u not in self.unitsOff]
        self.mSupply = len(self.unitsOn) * vdot * rho_sup

        # rack demand at the specified server dT
        self.mRack = self.load_W / (CP * p["serverDeltaT_K"])
        self.mDemand = self.mRack * self.n * 2
        rho_rack = P_ATM / (R_AIR * (self.Tsup + p["serverDeltaT_K"] / 2))
        self.rackArea = p["rackPitch"] * self.rackZ
        self.rackVel = self.mRack / (rho_rack * self.rackArea)
        self.fanSu = p["fanStiffness"] * self.rackVel
        self.fanSp = -p["fanStiffness"]

    # --- fan wall modules ---------------------------------------------------
    # A module is one fan/coil assembly with its own patch pair. Tag = end +
    # 1-based index, counted tier-major within each y slot: with one 40L2 per
    # end (modulesPerUnit 2), A1 = lower module, A2 = upper module of end A.
    def all_units(self) -> list:
        return [f"{end}{k*self.tiers + t + 1}"
                for end in "AB"
                for k in range(self.nUnits)
                for t in range(self.tiers)]

    def unit_y(self, k: int) -> tuple:
        y0 = self.uy0 + k * (self.p["unitWidth"] + self.unitGap)
        return y0, y0 + self.p["unitWidth"]

    def unit_window(self, tag: str) -> tuple:
        """(y0, y1, z0, z1) of the module's supply/return window."""
        idx = int(tag[1:]) - 1
        k, t = divmod(idx, self.tiers)
        y0, y1 = self.unit_y(k)
        base = t * self.moduleH
        return y0, y1, base + self.p["supplyZ0"], base + self.p["supplyZ1"]

    def unit_front_x(self, end: str) -> float:
        return self.ax1 if end == "A" else self.bx0

    def unit_rear_x(self, end: str) -> float:
        return self.ax0 if end == "A" else self.bx1

    def unit_dir(self, end: str) -> int:
        return +1 if end == "A" else -1

    # --- rack extents -----------------------------------------------------
    def rack(self, row: str, i: int) -> tuple:
        x0 = self.podX0 + i * self.p["rackPitch"]
        y0, y1 = (self.rowAy0, self.rowAy1) if row == "A" else (self.rowBy0, self.rowBy1)
        return x0, x0 + self.p["rackPitch"], y0, y1

    def front_y(self, row: str) -> float:
        return self.rowAy0 if row == "A" else self.rowBy1

    def flow_dir(self, row: str) -> int:
        return +1 if row == "A" else -1


def box(x0, y0, z0, x1, y1, z1) -> str:
    # .6g: at 50 mm cells the +-cellSize/4 tolerances need 6 significant
    # figures once x passes 10 m, or the rounding eats the tolerance.
    return f"({x0:.6g} {y0:.6g} {z0:.6g}) ({x1:.6g} {y1:.6g} {z1:.6g})"


def act(name, typ, action, source, extra="", **kw) -> str:
    body = "".join(f" {k} {v};" for k, v in kw.items())
    return (f"    {{ name {name}; type {typ}; action {action}; source {source};"
            f"{extra}{body} }}\n")


def write(path: Path, obj: str, payload: str) -> None:
    path.write_text(GEN + FOAM.format(obj) + "\n" + payload)


def main() -> int:
    case = Path(sys.argv[1] if len(sys.argv) > 1 else "case-hall")
    h = Hall(read_params(case))
    S, e = case / "system", h.eps

    # ---------------- blockMesh ----------------
    write(S / "blockMeshDict", "blockMeshDict", f"""scale 1;

vertices
(
    (0 0 0) ({h.Lx:.4g} 0 0) ({h.Lx:.4g} {h.Ly:.4g} 0) (0 {h.Ly:.4g} 0)
    (0 0 {h.zTop:.4g}) ({h.Lx:.4g} 0 {h.zTop:.4g})
    ({h.Lx:.4g} {h.Ly:.4g} {h.zTop:.4g}) (0 {h.Ly:.4g} {h.zTop:.4g})
);

blocks ( hex (0 1 2 3 4 5 6 7) ({h.nx} {h.ny} {h.nz}) simpleGrading (1 1 1) );

edges ();

boundary
(
    walls
    {{
        type wall;
        faces
        (
            (0 4 7 3) (1 2 6 5)     // x = 0, x = Lx
            (0 1 5 4) (3 7 6 2)     // y = 0, y = Ly
            (0 3 2 1) (4 5 6 7)     // floor, slab
        );
    }}
);
""")

    # ---------------- cut out the two fan wall units ----------------
    body = "actions\n(\n"
    body += act("roomCells", "cellSet", "new", "boxToCell",
                extra=f" box {box(-e,-e,-e, h.Lx+e, h.Ly+e, h.zTop+e)};")
    # With endBulkhead fitted, the infill panels are flush with the discharge
    # face, so the whole end slab below the plenum floor is solid - there is no
    # pocket beside the unit for air to eddy back into. Removing those cells is
    # both the physical truth and cheaper than meshing a sealed dead volume.
    # With intakeSide rear the slab starts at the unit REAR face, keeping the
    # return corridor between the slab and the end wall open.
    bulk = h.p.get("endBulkhead", 0) >= 0.5
    for x0, x1 in ((h.ax0, h.ax1), (h.bx0, h.bx1)):
        y0, y1 = (-e, h.Ly + e) if bulk else (h.uy0 + e, h.uy1 - e)
        body += act("roomCells", "cellSet", "subtract", "boxToCell",
                    extra=f" box {box(x0+e, y0, -e, x1-e, y1, h.p['unitHeight']-e)};")
    body += ");\n"
    write(S / "topoSetDict.units", "topoSetDict", body)

    # ---------------- supply + intake patches (one pair per module) --------
    body = "actions\n(\n"
    for u in h.all_units():
        xf = h.unit_front_x(u[0])
        y0, y1, z0, z1 = h.unit_window(u)
        body += act(f"fanWall{u}Faces", "faceSet", "new", "boxToFace",
                    extra=f" box {box(xf-e, y0+e, z0+e, xf+e, y1-e, z1-e)};")
    for u in h.all_units():
        y0, y1, z0, z1 = h.unit_window(u)
        if h.intakeSide == "top":
            x0, x1 = ((h.ax0, h.ax1) if u[0] == "A" else (h.bx0, h.bx1))
            bx = box(x0-e, y0+e, h.p['unitHeight']-e, x1+e, y1-e, h.p['unitHeight']+e)
        else:
            xr = h.unit_rear_x(u[0])
            bx = box(xr-e, y0+e, z0+e, xr+e, y1-e, z1-e)
        body += act(f"intake{u}Faces", "faceSet", "new", "boxToFace",
                    extra=f" box {bx};")
    body += ");\n"
    write(S / "topoSetDict.patches", "topoSetDict", body)

    unit_patches = [f"fanWall{u}" for u in h.all_units()] + \
                   [f"intake{u}" for u in h.all_units()]
    patches = "".join(
        f"    {{ name {n}; patchInfo {{ type patch; }} constructFrom set; set {n}Faces; }}\n"
        for n in unit_patches)
    write(S / "createPatchDict", "createPatchDict",
          f"pointSync false;\n\npatches\n(\n{patches});\n")

    # ---------------- solid internal surfaces ----------------
    body = "actions\n(\n"
    first = True

    def add(bx: str, comment: str = "") -> str:
        nonlocal first
        s = f"    // {comment}\n" if comment else ""
        s += act("internalWallFaces", "faceSet", "new" if first else "add",
                 "boxToFace", extra=f" box {bx};")
        first = False
        return s

    # plenum floor over the whole hall, then open the hot aisle riser and the
    # return path (unit tops, or the rear corridors) back up again. With
    # plenumHeight 0 there is no plenum at all: return air travels through the
    # open room above the containment (rear intake only).
    if h.plenum:
        body += add(box(-e, -e, h.p["plenumFloorZ"] - e, h.Lx + e, h.Ly + e,
                        h.p["plenumFloorZ"] + e), "plenum floor")
        body += act("internalWallFaces", "faceSet", "subtract", "boxToFace",
                    extra=f" box {box(h.podX0-e, h.hotY0-e, h.p['plenumFloorZ']-e, h.podX1+e, h.hotY1+e, h.p['plenumFloorZ']+e)};")
        if h.intakeSide == "top":
            for x0, x1 in ((h.ax0, h.ax1), (h.bx0, h.bx1)):
                body += act("internalWallFaces", "faceSet", "subtract", "boxToFace",
                            extra=f" box {box(x0-e, h.uy0-e, h.p['plenumFloorZ']-e, x1+e, h.uy1+e, h.p['plenumFloorZ']+e)};")
        else:
            for x0, x1 in ((0.0, h.ax0), (h.bx1, h.Lx)):
                body += act("internalWallFaces", "faceSet", "subtract", "boxToFace",
                            extra=f" box {box(x0-e, -e, h.p['plenumFloorZ']-e, x1+e, h.Ly+e, h.p['plenumFloorZ']+e)};")

    # rack tops and row end walls
    for y0, y1 in ((h.rowAy0, h.rowAy1), (h.rowBy0, h.rowBy1)):
        body += add(box(h.podX0-e, y0+e, h.rackZ-e, h.podX1+e, y1-e, h.rackZ+e), "rack tops")
        for xf in (h.podX0, h.podX1):
            body += add(box(xf-e, y0+e, -e, xf+e, y1-e, h.rackZ+e), "row end wall")

    # containment above the racks, and the hot aisle end doors
    for yf in (h.hotY0, h.hotY1):
        body += add(box(h.podX0-e, yf-e, h.rackZ-e, h.podX1+e, yf+e, h.contZ+e),
                    "containment panel above racks")
    doorTop = (h.p["plenumFloorZ"] if h.p.get("sealEndDoors", 0) >= 0.5 else h.contZ)
    for xf in (h.podX0, h.podX1):
        body += add(box(xf-e, h.hotY0+e, -e, xf+e, h.hotY1-e, doorTop+e),
                    "hot aisle end door")

    body += act("internalWallsZone", "faceZoneSet", "new", "setToFaceZone",
                extra=" faceSet internalWallFaces;")
    body += ");\n"
    write(S / "topoSetDict.baffles", "topoSetDict", body)

    write(S / "createBafflesDict", "createBafflesDict", """internalFacesOnly true;
fields false;

baffles
{
    internalWalls
    {
        type faceZone; zoneName internalWallsZone;
        patches
        {
            master { name internalWalls;       type wall; }
            slave  { name internalWalls_slave; type wall; }
        }
    }
}
""")

    # ---------------- rack zones and metrics ----------------
    body = "actions\n(\n"
    body += act("hotAisleCells", "cellSet", "new", "boxToCell",
                extra=f" box {box(h.podX0-e, h.hotY0+e, -e, h.podX1+e, h.hotY1-e, h.p['plenumFloorZ']-e)};")
    for row in ("A", "B"):
        for i in range(h.n):
            x0, x1, y0, y1 = h.rack(row, i)
            t = f"{row}{i:02d}"
            body += act(f"rackCells_{t}", "cellSet", "new", "boxToCell",
                        extra=f" box {box(x0+e, y0+e, -e, x1-e, y1-e, h.rackZ-e)};")
            body += act(f"rack_{t}", "cellZoneSet", "new", "setToCellZone",
                        extra=f" set rackCells_{t};")
            yf = h.front_y(row)
            body += act(f"inletFaces_{t}", "faceSet", "new", "boxToFace",
                        extra=f" box {box(x0+e, yf-e, -e, x1-e, yf+e, h.rackZ-e)};")
            body += act(f"inlet_{t}", "faceZoneSet", "new", "setsToFaceZone",
                        extra=f" faceSet inletFaces_{t}; cellSet rackCells_{t}; flip true;")
    body += ");\n"
    write(S / "topoSetDict.racks", "topoSetDict", body)

    # ---------------- sources ----------------
    fv = [GEN, FOAM.format("fvOptions"), ""]
    fv.append(f"// {2*h.n} racks x {h.p['rackLoad_kW']:g} kW = "
              f"{2*h.n*h.p['rackLoad_kW']:g} kW total.\n"
              f"// Server fans hold {h.rackVel:.3f} m/s, which is "
              f"{h.mRack:.3f} kg/s per rack at dT = {h.p['serverDeltaT_K']:g} K.\n")
    for row in ("A", "B"):
        d = h.flow_dir(row)
        for i in range(h.n):
            t = f"{row}{i:02d}"
            fv.append(f"""
rackHeat_{t}
{{
    type scalarSemiImplicitSource; selectionMode cellZone; cellZone rack_{t};
    volumeMode absolute;
    sources {{ h ({h.load_W:g} 0); }}
}}

rackFans_{t}
{{
    type vectorSemiImplicitSource; selectionMode cellZone; cellZone rack_{t};
    volumeMode specific;
    sources {{ U ((0 {d*h.fanSu:.4g} 0) {h.fanSp:g}); }}
}}""")
    (S / "fvOptions").write_text("".join(fv) + "\n")

    # ---------------- per-rack metrics ----------------
    fo = [GEN]
    for row in ("A", "B"):
        for i in range(h.n):
            t = f"{row}{i:02d}"
            fo.append(f"""
r{t}_inletT
{{
    type surfaceFieldValue; libs (fieldFunctionObjects);
    regionType faceZone; name inlet_{t};
    operation areaAverage; fields (T);
    writeFields false; writeControl timeStep; writeInterval 20; log false;
}}
r{t}_inletTmax {{ $r{t}_inletT; operation max; }}
r{t}_flow      {{ $r{t}_inletT; operation sum; fields (phi); }}""")
    (S / "hallFunctions").write_text("".join(fo) + "\n")

    # ---------------- boundary conditions ----------------
    # Unit A discharges +x, unit B discharges -x. Generated so the signs cannot
    # be mistyped.
    Z = case / "0.orig"
    Z.mkdir(exist_ok=True)
    WALLS = '"(walls|unitWalls|internalWalls.*)"'
    k_in = 1.5 * (0.05 * h.supplyVel) ** 2
    om_in = k_in ** 0.5 / (0.09 ** 0.25 * 0.2)
    Tret = h.Tsup + h.p["serverDeltaT_K"]

    def field(name, cls, dims, internal, entries):
        body = (GEN + f"FoamFile {{ version 2.0; format ascii; class {cls}; "
                f"object {name}; }}\n\n"
                f"dimensions      {dims};\n\n"
                f"internalField   uniform {internal};\n\nboundaryField\n{{\n")
        for pat, spec in entries:
            body += f"    {pat}\n    {{\n"
            for kk, vv in spec:
                body += f"        {kk:<15} {vv};\n"
            body += "    }\n\n"
        (Z / name).write_text(body + "}\n")

    v = h.supplyVel
    on = h.unitsOn
    off = [u for u in h.all_units() if u in h.unitsOff]

    U_entries = []
    for u in on:
        d = h.unit_dir(u[0])
        U_entries.append((f"fanWall{u}", [("type", "fixedValue"),
                                          ("value", f"uniform ({d*v:.5g} 0 0)")]))
        U_entries.append((f"intake{u}", [("type", "pressureInletOutletVelocity"),
                                         ("value", "uniform (0 0 0)")]))
    for u in off:   # stopped module: discharge damper closed, no through-flow
        for pfx in ("fanWall", "intake"):
            U_entries.append((f"{pfx}{u}", [("type", "fixedValue"),
                                            ("value", "uniform (0 0 0)")]))
    U_entries.append((WALLS, [("type", "noSlip")]))
    field("U", "volVectorField", "[0 1 -1 0 0 0 0]", "(0 0 0)", U_entries)

    T_entries = []
    for u in on:
        T_entries.append((f"fanWall{u}", [("type", "fixedValue"),
                                          ("value", f"uniform {h.Tsup:.5g}")]))
        T_entries.append((f"intake{u}", [("type", "inletOutlet"),
                                         ("inletValue", f"uniform {Tret:.5g}"),
                                         ("value", f"uniform {Tret:.5g}")]))
    for u in off:
        for pfx in ("fanWall", "intake"):
            T_entries.append((f"{pfx}{u}", [("type", "zeroGradient")]))
    T_entries.append((WALLS, [("type", "zeroGradient")]))
    field("T", "volScalarField", "[0 0 0 1 0 0 0]", f"{h.Tsup:.5g}", T_entries)

    prgh_entries = []
    for u in on:
        prgh_entries.append((f"fanWall{u}", [("type", "fixedFluxPressure"),
                                             ("value", "uniform 101325")]))
        prgh_entries.append((f"intake{u}", [("type", "fixedValue"),
                                            ("value", "uniform 101325")]))
    for u in off:
        for pfx in ("fanWall", "intake"):
            prgh_entries.append((f"{pfx}{u}", [("type", "fixedFluxPressure"),
                                               ("value", "uniform 101325")]))
    prgh_entries.append((WALLS, [("type", "fixedFluxPressure"),
                                 ("value", "uniform 101325")]))
    field("p_rgh", "volScalarField", "[1 -1 -2 0 0 0 0]", "101325", prgh_entries)

    field("p", "volScalarField", "[1 -1 -2 0 0 0 0]", "101325", [
        ('".*"', [("type", "calculated"), ("value", "uniform 101325")]),
    ])

    ALLU = '"(fanWall|intake)(A|B)[0-9]+"'
    k_entries = [(f"fanWall{u}", [("type", "fixedValue"),
                                  ("value", f"uniform {k_in:.5g}")]) for u in on]
    k_entries += [(f"intake{u}", [("type", "inletOutlet"),
                                  ("inletValue", f"uniform {k_in:.5g}"),
                                  ("value", f"uniform {k_in:.5g}")]) for u in on]
    k_entries += [(f"{pfx}{u}", [("type", "zeroGradient")])
                  for u in off for pfx in ("fanWall", "intake")]
    k_entries.append((WALLS, [("type", "kqRWallFunction"),
                              ("value", f"uniform {k_in:.5g}")]))
    field("k", "volScalarField", "[0 2 -2 0 0 0 0]", f"{k_in:.5g}", k_entries)

    om_entries = [(f"fanWall{u}", [("type", "fixedValue"),
                                   ("value", f"uniform {om_in:.5g}")]) for u in on]
    om_entries += [(f"intake{u}", [("type", "inletOutlet"),
                                   ("inletValue", f"uniform {om_in:.5g}"),
                                   ("value", f"uniform {om_in:.5g}")]) for u in on]
    om_entries += [(f"{pfx}{u}", [("type", "zeroGradient")])
                   for u in off for pfx in ("fanWall", "intake")]
    om_entries.append((WALLS, [("type", "omegaWallFunction"),
                               ("value", f"uniform {om_in:.5g}")]))
    field("omega", "volScalarField", "[0 0 -1 0 0 0 0]", f"{om_in:.5g}", om_entries)

    field("nut", "volScalarField", "[0 2 -1 0 0 0 0]", "0", [
        (WALLS, [("type", "nutkWallFunction"), ("value", "uniform 0")]),
        (ALLU, [("type", "calculated"), ("value", "uniform 0")]),
    ])
    field("alphat", "volScalarField", "[1 -1 -1 0 0 0 0]", "0", [
        (WALLS, [("type", "compressible::alphatWallFunction"), ("Prt", "0.85"),
                 ("value", "uniform 0")]),
        (ALLU, [("type", "calculated"), ("value", "uniform 0")]),
    ])

    # ---------------- controlDict ----------------
    ranks = 8
    (S / "decomposeParDict").write_text(
        GEN + FOAM.format("decomposeParDict") +
        f"\nnumberOfSubdomains {ranks};\nmethod scotch;\n")

    first_unit = h.all_units()[0]
    unit_fos = f"""    supply{first_unit}
    {{
        type surfaceFieldValue; libs (fieldFunctionObjects);
        regionType patch; name fanWall{first_unit}; operation sum; fields (phi);
        writeFields false; writeControl timeStep; writeInterval 20; log false;
    }}
"""
    for u in h.all_units():
        if u != first_unit:
            unit_fos += f"    supply{u}  {{ $supply{first_unit}; name fanWall{u}; }}\n"
        unit_fos += f"    return{u}  {{ $supply{first_unit}; name intake{u}; }}\n"
        unit_fos += (f"    returnT{u} {{ $supply{first_unit}; name intake{u}; "
                     f"operation areaAverage; fields (T); }}\n")

    (S / "controlDict").write_text(GEN + FOAM.format("controlDict") + f"""
application     buoyantSimpleFoam;
startFrom       startTime;  startTime 0;
stopAt          endTime;    endTime   4000;
deltaT          1;
writeControl    timeStep;   writeInterval 1000;   purgeWrite 2;
// binary: at 6.9 M cells ascii field writes dominate the runtime and the
// plotting tools read postProcessing text files and VTK, both fine with it.
writeFormat     binary;     writePrecision 8;     writeCompression off;
timeFormat      general;    timePrecision 6;
runTimeModifiable true;

functions
{{
    // ---- per-module supply / return aggregates ----
{unit_fos}
    residuals
    {{
        type solverInfo; libs (utilityFunctionObjects);
        fields (U p_rgh h k omega); writeControl timeStep; writeInterval 1;
    }}
    limits
    {{
        type fieldMinMax; libs (fieldFunctionObjects);
        fields (T U); writeControl timeStep; writeInterval 20; log false;
    }}

    // ---- per-rack metrics (generated) ----
    #include "hallFunctions"

    // Sampled in-run and in-parallel, so the case never has to be reconstructed.
    sampledSlices
    {{
        #include "slices"
    }}

    TdegC
    {{
        type expressions; libs (fieldFunctionObjects); writeControl writeTime;
        expressions ( {{ name TdegC; dimensions [0 0 0 1 0 0 0];
                        expression "T - 273.15"; }} );
    }}
}}
""")

    (S / "slices").write_text(GEN + f"""
type                surfaces;
libs                (sampling);
writeControl        onEnd;
surfaceFormat       raw;
interpolationScheme cellPoint;
fields              (T U);

surfaces
{{
    coldAisleA  // plan slice at rack mid-height
    {{
        type plane; planeType pointAndNormal;
        pointAndNormalDict {{ point (0 0 {h.rackZ/2:.4g}); normal (0 0 1); }}
        interpolate true;
    }}
    rowAcentre  // vertical slice along row A
    {{
        type plane; planeType pointAndNormal;
        pointAndNormalDict {{ point (0 {(h.rowAy0+h.rowAy1)/2:.4g} 0); normal (0 1 0); }}
        interpolate true;
    }}
    hallCentre  // vertical slice down the hot aisle
    {{
        type plane; planeType pointAndNormal;
        pointAndNormalDict {{ point (0 {(h.hotY0+h.hotY1)/2:.4g} 0); normal (0 1 0); }}
        interpolate true;
    }}
}}
""")

    # ---------------- report ----------------
    tot = 2 * h.n * h.p["rackLoad_kW"]
    nOn = len(h.unitsOn)
    cap = nOn * h.p["unitCapacity_kW"]
    print(f"  hall            {h.Lx:g} x {h.Ly:g} x {h.zTop:g} m"
          f"   mesh {h.nx} x {h.ny} x {h.nz} = {h.nx*h.ny*h.nz:,} cells")
    nMod = h.nUnits * h.tiers
    print(f"  fan walls       {2*nMod} x {h.p['unitCapacity_kW']:g} kW modules"
          f" ({h.nUnits} wide x {h.tiers} high per end, intake {h.intakeSide}"
          + (f", rear corridor {h.rearGap:g} m" if h.rearGap else "")
          + (f", OFF: {' '.join(sorted(h.unitsOff))}" if h.unitsOff else "")
          + (", no ceiling plenum" if not h.plenum else "") + ")")
    print(f"  racks           {2*h.n} x {h.p['rackLoad_kW']:g} kW = {tot:g} kW"
          f"   vs {cap:g} kW running capacity ({100*tot/cap:.0f} %)")
    print(f"  supply          {h.mSupply:.2f} kg/s at {h.supplyVel:.2f} m/s"
          f"  ({h.supplyArea:.1f} m2 per module, {nOn} running)")
    print(f"  rack demand     {h.mDemand:.2f} kg/s  ->  supply/demand "
          f"{h.mSupply/h.mDemand:.3f}")
    print(f"  per rack        {h.mRack:.3f} kg/s at {h.rackVel:.3f} m/s")
    print(f"  containment gap {h.p['containmentGap']:g} m below the plenum floor"
          f" (side panels{'; end doors SEALED' if h.p.get('sealEndDoors',0)>=0.5 else '; ends open'})")
    print(f"  rack            {h.p['rackPitch']*1000:.0f} w x {h.p['rackDepth']*1000:.0f} d"
          f" x {h.rackZ*1000:.0f} h mm (42U snapped), free face {h.rackArea:.2f} m2")
    print(f"  cold aisles     {h.sideA*1000:.0f} mm and {h.sideB*1000:.0f} mm"
          f"  (asymmetry {abs(h.sideA-h.sideB)*1000:.0f} mm = "
          f"{abs(h.sideA-h.sideB)/h.c:.0f} cell)")
    print(f"  hot aisle       {h.p['hotAisleWidth']*1000:.0f} mm wide"
          f", riser {h.rowLen*h.p['hotAisleWidth']:.2f} m2")
    print(f"  unit y offset   {h.unitOffset*1000:+.0f} mm from the hall centreline (grid snap)")
    print(f"  end bulkhead    {'FITTED flush with the discharge face' if h.p.get('endBulkhead',0)>=0.5 else 'none - open ends'}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
