#!/bin/sh
cd "${0%/*}" || exit 1
. "${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions"

cleanCase0
rm -rf postProcessing constant/polyMesh
rm -f case.foam

#------------------------------------------------------------------------------
